name: 'data_architecture_comparison'
version: '1.0.0'
config-version: 2

profile: 'data_architecture_comparison'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']

models:
  data_architecture_comparison:
    staging:
      +materialized: view
    marts:
      +materialized: table
